#!/bin/bash

sudo apt-get install software-properties-common python-software-properties && sudo add-apt-repository "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main"  && sudo apt-get update && sudo apt-get install oracle-java8-installer
